# Generated by Django 3.2.15 on 2022-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRatePLN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("CHF", "CHF"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
