# Generated by Django 3.2.15 on 2022-09-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangeratepln',
            unique_together={('date', 'currency')},
        ),
    ]
